DROP TABLE dose CASCADE CONSTRAINTS;
DROP TABLE vacina CASCADE CONSTRAINTS;
DROP TABLE cidadao CASCADE CONSTRAINTS;
DROP TABLE posto CASCADE CONSTRAINTS;
DROP TABLE possui CASCADE CONSTRAINTS;
DROP SEQUENCE s_dose;
DROP SEQUENCE s_cidadao;
DROP SEQUENCE s_posto;
DROP SEQUENCE s_vacina;