

DROP TABLE dose CASCADE CONSTRAINTS;
DROP TABLE vacina CASCADE CONSTRAINTS;
DROP TABLE cidadao CASCADE CONSTRAINTS;
DROP TABLE posto CASCADE CONSTRAINTS;
DROP TABLE possui CASCADE CONSTRAINTS;

DROP SEQUENCE s_dose;
DROP SEQUENCE s_cidadao;
DROP SEQUENCE s_posto;
DROP SEQUENCE s_vacina;

DROP PROCEDURE PRC_ATUALIZA_DOSE;
DROP PROCEDURE PRC_ATUALIZA_RETORNO;
DROP PROCEDURE PRC_DADOS;
DROP PROCEDURE PRC_FAIXA_ETARIA;

DROP FUNCTION FNC_DOSE;
DROP FUNCTION FNC_IDADE;
DROP FUNCTION FNC_MEDIA_IDADE;
DROP FUNCTION FNC_VACINA;

