CREATE OR REPLACE FUNCTION FNC_DOSE(P_ID_CIDADAO IN NUMBER)
  RETURN DATE IS
  --Retorna a ultima data da aplicação (Máxima)
  --Utilizar no SELECT
  DT_APLICA DATE;

BEGIN
  SELECT MAX(DATA_APLICACAO)
  INTO   DT_APLICA
  FROM   DOSE
  WHERE  ID_CIDADAO = P_ID_CIDADAO;

  RETURN(DT_APLICA);
END FNC_DOSE;


--Utilizar no SELECT
--SELECT ID_CIDADAO, NOME, FNC_DOSE(ID_CIDADAO) "ULTIMA DATA"
--FROM CIDADAO
--ORDER BY NOME;
/
