CREATE OR REPLACE FUNCTION FNC_IDADE(P_ID_CIDADAO IN NUMBER)
  RETURN NUMBER IS
  --Retorna a IDADE do CIDADAO
  --Utilizar no SELECT
  IDADE NUMBER;

BEGIN
  SELECT TRUNC((SYSDATE - DT_NASCIMENTO) /365)
    INTO IDADE
    FROM CIDADAO
   WHERE ID_CIDADAO = P_ID_CIDADAO;

  RETURN(IDADE);
END FNC_IDADE;

--Utilizar no SELECT
--SELECT ID_CIDADAO, NOME, FNC_IDADE(ID_CIDADAO) IDADE
--FROM CIDADAO
--ORDER BY NOME;
/
