CREATE OR REPLACE PROCEDURE PRC_ATUALIZA_RETORNO IS

  --Atualiza DATA_RETORNO
  --Atualiza todas as linhas da tabela DOSE conforme parâmetros
  --Chamada no trigger TRG_AFTER_U_VACINA
  
BEGIN
  FOR R_VACINA IN (SELECT * FROM VACINA)
    LOOP
    UPDATE DOSE
    SET    DATA_RETORNO = DATA_APLICACAO + R_VACINA.TEMPO_ENTRE_APLICACOES
    WHERE  ID_VACINA = R_VACINA.ID_VACINA;
  END LOOP;
 
END PRC_ATUALIZA_RETORNO;
/
