CREATE OR REPLACE TRIGGER TRG_AFTER_U_VACINA
  AFTER UPDATE OF TEMPO_ENTRE_APLICACOES ON VACINA

  --Atualiza DATA_RETORNO na tabela DOSE
  --Após alteração da coluna TEMPO_ENTRE_APLICACOES da tabela VACINA

BEGIN
  PRC_ATUALIZA_RETORNO;

END TRG_AFTER_U_VACINA;
/
